USE MASTER
GO
IF EXISTS ( SELECT * FROM SYS.DATABASES WHERE NAME = 'QUANLYSINHVIEN')
	DROP DATABASE QUANLYSINHVIEN
GO

CREATE DATABASE QUANLYSINHVIEN
GO

USE QUANLYSINHVIEN
ALTER DATABASE QUANLYSINHVIEN COLLATE Vietnamese_CI_AS
--CREATE TABLE
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME = 'tblStudent')
	DROP TABLE tblStudent
GO
CREATE TABLE tblStudent
(
	STUDENTID NVARCHAR(20) NOT NULL,
	FULLNAME NVARCHAR(20),
	AVERAGESCORE FLOAT,
	FACULTYID INT,
)
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME = 'tblFaculty')
	DROP TABLE tblFaculty
GO
CREATE TABLE tblFaculty
(
	FACULTYID INT NOT NULL,
	FACULTYNAME NVARCHAR(200)
)
ALTER TABLE tblStudent 
	ADD CONSTRAINT PK_tblStudent PRIMARY KEY (STUDENTID)
ALTER TABLE tblFaculty 
	ADD CONSTRAINT PK_tblFaculty PRIMARY KEY (FACULTYID)
ALTER TABLE tblStudent
	ADD CONSTRAINT FK_tblStudent_tblFaculty FOREIGN KEY(FACULTYID) REFERENCES tblFaculty(FACULTYID)


INSERT INTO tblFaculty(FACULTYID,FACULTYNAME) VALUES('1','CNTT')
INSERT INTO tblFaculty(FACULTYID,FACULTYNAME) VALUES('2','NNA')
INSERT INTO tblFaculty(FACULTYID,FACULTYNAME) VALUES('3','QTKD')

INSERT INTO tblStudent(STUDENTID,FULLNAME,AVERAGESCORE,FACULTYID) VALUES('ID1', N'STUDENT 1', '6.7','1')
INSERT INTO tblStudent(STUDENTID,FULLNAME,AVERAGESCORE,FACULTYID) VALUES('ID2', N'STUDENT 2', '6.9','3')
INSERT INTO tblStudent(STUDENTID,FULLNAME,AVERAGESCORE,FACULTYID) VALUES('ID3', N'STUDENT 3', '10','2')
INSERT INTO tblStudent(STUDENTID,FULLNAME,AVERAGESCORE,FACULTYID) VALUES('ID4', N'STUDENT 4', '8','1')
INSERT INTO tblStudent(STUDENTID,FULLNAME,AVERAGESCORE,FACULTYID) VALUES('ID5', N'STUDENT 5', '9','2')
INSERT INTO tblStudent(STUDENTID,FULLNAME,AVERAGESCORE,FACULTYID) VALUES('ID6', N'STUDENT 6', '1','3')


SELECT * FROM tblFaculty
SELECT * FROM tblStudent